### ISSUE TITLE
Connection issue reported by arch linux user named @myknbani

### ISSUE THREAD

**Issue by mearaj** [mearaj/nordlayer#6]
Login: Logged in
VPN: Failed
Current network: House Tully
Gateway: GrowSurf Private Gateway
Server address: 104.200.145.164
Protocol: OpenVPN UDP

VPN shows failed even if I'm actually connected. Also reached out to Nordlayer support but got the blunt "Only Ubuntu and Fedora" are supported response.

Also disconnecting and reconnecting makes it get stuck at "Connecting..."

**Comment by mearaj** [comment]
Possible solutions
1. Please have a look at [linux connection issues](https://help.nordlayer.com/docs/unable-to-connect-to-nordlayer-service-on-linux)

**Comment by myknbani** [comment]
Thanks @mearaj ,  I'm actually connected, based on the IP address, and the fact that I can access our IP-whitelisted servers.  But `nordlayer s` shows 

```
Login: Logged in
VPN: Failed
Current network: House Targaryen
Gateway: GrowSurf Private Gateway
Server address: 104.200.145.164
Protocol: OpenVPN UDP
```

For connection protocol: Only UDP gives me the most speed, TCP is too slow, and the others won't connect.  It works for now, even with the inaccurate status shown,.

**Comment by mearaj** [comment]
Hi @myknbani ,
Thanks  for reporting it.
I just need little time to look into it.
There are others also complaining and I am also facing this same issue.
Will let you know ASAP.
Thanks :)

**Comment by myknbani** [comment]
Hi @mearaj  the lastest version works.  Thanks for the fix :-)

**Comment by mearaj** [comment]
> Hi @mearaj the lastest version works. Thanks for the fix :-)

Thank you :)

**Comment by mearaj** [comment]
Closing this issue as commit b947485787f8f66fcf4c1638f2db7077e69de2ef resolves it.
Thanks :)
