### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by skrat** [mearaj/nordlayer#7]
So 1st issue was "fork/exec: permission denied" on `/usr/sbin/nordlayer-resolvconf` which is owned by root and only executable by root. So naturally the service running under `nordlayer` user/group can't run that. I tried to work around by making it executable by other, and then also chowning to `nordlayer`. It fixed the original issue, but now I'm getting

```
Dec 05 12:02:42 crowsnest nordlayerd[1037167]: time="2022-12-05T12:02:42-07:00" level=info msg="3running cmd" arg="[save]" component=dns name=/usr/sbin/nordlayer-resolvconf procedure=exec
Dec 05 12:02:42 crowsnest nordlayerd[1037167]: ERRO[0083] exit status 3                            component=vpn procedure=proc_queue
```

Which, again, looks like some sort of permission denied issue, I get the same exit code when I run that binary with no arguments under `nordlayer` user. It displays help when I run it as root. That might be the issue here but I've no idea how to solve it other than running everything as root instead of `nordlayer`.

**Comment by mearaj** [comment]
Hi @skrat,
Thanks for reporting it. 
I just need little time to look into it.
There are others also complaining and I myself facing issues now.
Will let you know ASAP.

**Comment by skrat** [comment]
Got this response from Nordlayer, and indeed, after I applied this, everything started to work as expected. So this should go into the PKGBUILD (Except the path I have to `nordlayer-resolveconf` is `/usr/sbin/nordlayer-resolvconf`

Hello,
 
I am contacting you regarding your recent chat session.
 
In order to run the NordLayer application on an ARCH Linux system, you would need to have your packager update the install scripts if the application package is downloaded from [this repository](https://aur.archlinux.org/packages/nordlayer).
 
Otherwise, it can be done by performing the following steps:
 
1. Add `nordlayer-resolve` group;
2. Add `nordlayer` to `nordlayer-resolve` group;
3. Extract `nordlayer-resolveconf` binary form .deb package if it is missing, then run the following commands:
`chown root:nordlayer-resolve /usr/bin/nordlayer-resolvconf`
`chmod 4750 /usr/bin/nordlayer-resolveconf`
 
Let us know how it goes.

**Comment by mearaj** [comment]
Hi @skrat,
Thanks a lot.
I will try it out and get back to you.

**Comment by mearaj** [comment]
Hi @skrat ,
I have followed the instructions you provided and also checked with debian package.
I hope your issue is resolved now.
Thanks for sharing the resolution. :)
